---
title: "PA 3.1"
author: "Chloe Feehan"
format: 
  html:
    code-fold: true
    embed-resources: true
    toc: true
theme: flatly
---

In [26]:
import numpy as np
import pandas as pd

colleges = pd.read_csv("https://www.dropbox.com/s/bt5hvctdevhbq6j/colleges.csv?dl=1")

In [28]:
# narrow down columns of interest
colleges_clean = colleges[['INSTNM', 'CITY', 'STABBR', 'ZIP', 'CONTROL', 'ADM_RATE', 'SAT_AVG', 'TUITIONFEE_IN', 'TUITIONFEE_OUT', 'UGDS', 'REGION']]

# remove schools not needed (category 3)
colleges_clean = colleges_clean[colleges_clean['CONTROL'] != 3]

# adjust to be numeric
colleges_clean['TUITIONFEE_IN'] = colleges_clean['TUITIONFEE_IN'].astype('float')

colleges_clean['TUITIONFEE_OUT'] = colleges_clean['TUITIONFEE_OUT'].astype('float')

colleges_clean['SAT_AVG'] = colleges_clean['SAT_AVG'].astype('float')

colleges_clean['ADM_RATE'] = colleges_clean['ADM_RATE'].astype('float')

# adjust categorical
colleges_clean["CONTROL"] = colleges_clean['CONTROL'].astype('category')
colleges_clean["REGION"] = colleges_clean['REGION'].astype('category')

# Create a new variable called TUITION_DIFF which contains 
# the difference between in and out of state costs.

colleges_clean['TUITION_DIFF'] = colleges_clean["TUITIONFEE_OUT"] - colleges_clean["TUITIONFEE_IN"]

# drop na values
colleges_clean = colleges_clean.dropna()

Identify the mystery college

This college is located in Region 1.

This college's admission rate is in the first quartile for the region.

This college charges the same for in- and out-of-state tuition.

The average SAT score of this college is an odd number.

This college is NOT in New Hampshire or in the city of Boston.

More than 3,000 people apply to this college every year. (Hint: Make a new variable to compute how many people apply. Assume the size of an incoming class is 1/4 of the total undergraduate population, and remember that not everyone who applies is admitted.)

Ephelia is not going to an Ivy League school.

Of the two options remaining at this step, Ephelia will attend the cheaper one.

In [48]:
# filter by college located in Region 1.
mystery = colleges_clean[colleges_clean["REGION"] == 1]

#This college's admission rate is in the first quartile for the region

# This college charges the same for in- and out-of-state tuition
mystery = mystery[mystery["TUITION_DIFF"] == 0]

# The average SAT score of this college is an odd number
mystery = mystery[mystery["SAT_AVG"] % 2 != 0]

# This college is NOT in New Hampshire or in the city of Boston.
mystery = mystery[(mystery["CITY"] != "Boston")]
mystery = mystery[(mystery["STABBR"] != "NH")]

#More than 3,000 people apply to this college every year. (Hint: Make a new variable to 
# compute how many people apply. Assume the size of an incoming class is 1/4 of the 
# total undergraduate population, and remember that not everyone who applies is admitted.)
mystery["INCOMING_CLASS"] = mystery["UGDS"] / 4

mystery["APPLICANTS"] = mystery["INCOMING_CLASS"] / mystery["ADM_RATE"]

mystery = mystery[mystery["APPLICANTS"] > 3000]
mystery

                  INSTNM          CITY STABBR         ZIP  ... REGION  TUITION_DIFF  INCOMING_CLASS    APPLICANTS
1500     Amherst College       Amherst     MA  01002-5000  ...      1           0.0          458.75   3556.201550
1549  Harvard University     Cambridge     MA        2138  ...      1           0.0         1883.00  36492.248062
1619    Williams College  Williamstown     MA        1267  ...      1           0.0          508.25   3485.939643

[3 rows x 14 columns]